name: Build macOS binaries of Ungoogled Chromium
on:
  workflow_dispatch:
  push:
    paths:
      - 'patches/**'
      - 'downloads**.ini'
      - 'revision.txt'
      - 'flags.macos.gn'
      - '!build.sh'
      - '!README.md'
      - '!LICENSE'
      - '!devutils/**'
      - '.github/scripts/force_build.txt'

jobs:
  build:
    name: Build macOS binaries of Ungoogled Chromium
    strategy:
      matrix:
        arch: [arm64]
        include:
          - arch: arm64
            os: macos-14
      fail-fast: true
      max-parallel: 2
    uses: ./.github/workflows/building.yml
    with:
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os }}

  release:
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: Release macOS binaries of Ungoogled Chromium
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Copy GitHub specific scripts to git-root folder
        run: cp -va ./.github/scripts/ ./
      - name: Disable Spotlight
        run: sudo mdutil -a -i off
      - name: Install coreutils
        run: brew install coreutils
      - name: Prepare release
        id: bake
        run: ./github_prepare_release.sh | tee -a github_actions_release.log
